name: Release

on:
  push:
    branches:
      - main
      - next
      - next-major
      - rc
      - alpha
      - beta

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Configure NodeJS version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Audit modules
        run: npm audit --audit-level=critical
      - name: Install dependencies
        run: npm ci
      - name: Trigger a new release
        run: ./node_modules/.bin/semantic-release
