name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14
          - 16
          - 18

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Audit packages (fail if any critical module is identified)
        run: npm audit --audit-level=critical
      - name: Install dependencies
        run: npm ci
